/*
 * dialog_IngresarCodigoReserva.java
 *
 * Created on Oct 22, 2011, 10:15:39 AM
 */
package frontera;


import control.AdministrarReserva;
import control.BusquedaDeHabitaciones;
import control.IOHuespedes;
import entidad.Habitacion;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author juancho
 */
public class dialog_CheckOut extends javax.swing.JDialog {

    private Hosys parent;
    private BusquedaDeHabitaciones reserva = new BusquedaDeHabitaciones();

    /** Creates new form dialog_IngresarCodigoReserva */
    public dialog_CheckOut(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (Hosys) parent;

        ArrayList<Habitacion> habitacionesOcupadas = reserva.habitacionesOcupadas();
        if (!habitacionesOcupadas.isEmpty()) {
            for (Habitacion j : habitacionesOcupadas) {
                comboBox_HabitacionesDisponibles.addItem(j.getIdHabitacion());
            }
            button_GenerarFactura.setEnabled(true);
        } else {
            button_GenerarFactura.setEnabled(false);
        }
        label_Titulo.requestFocusInWindow();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Titulo = new javax.swing.JLabel();
        label_Info = new javax.swing.JLabel();
        panel_HabitacionesDisponibles = new javax.swing.JPanel();
        button_GenerarFactura = new javax.swing.JButton();
        button_Volver = new javax.swing.JButton();
        comboBox_HabitacionesDisponibles = new javax.swing.JComboBox();
        label_HabitacionesDisponibles = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hosys - Login");

        label_Titulo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        label_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/l/upload.png"))); // NOI18N
        label_Titulo.setText("Check-Out");
        label_Titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        label_Titulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        label_Titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                label_TituloKeyReleased(evt);
            }
        });

        label_Info.setText("Por favor, Ingrese el número de la habitación");
        label_Info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_HabitacionesDisponiblesLayout = new javax.swing.GroupLayout(panel_HabitacionesDisponibles);
        panel_HabitacionesDisponibles.setLayout(panel_HabitacionesDisponiblesLayout);
        panel_HabitacionesDisponiblesLayout.setHorizontalGroup(
            panel_HabitacionesDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_HabitacionesDisponiblesLayout.setVerticalGroup(
            panel_HabitacionesDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        button_GenerarFactura.setText("Generar Factura");
        button_GenerarFactura.setEnabled(false);
        button_GenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_GenerarFacturaActionPerformed(evt);
            }
        });

        button_Volver.setText("Volver");
        button_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_VolverActionPerformed(evt);
            }
        });

        comboBox_HabitacionesDisponibles.setModel(new javax.swing.DefaultComboBoxModel());

        label_HabitacionesDisponibles.setText("Numero de habitación:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_GenerarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_Volver))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_HabitacionesDisponibles)
                        .addGap(68, 68, 68)
                        .addComponent(panel_HabitacionesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox_HabitacionesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(label_Info, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_HabitacionesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_Volver)
                            .addComponent(button_GenerarFactura)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_HabitacionesDisponibles)
                        .addComponent(comboBox_HabitacionesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_GenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_GenerarFacturaActionPerformed
        new IOHuespedes().LiquidarHuesped(new AdministrarReserva().ConsultarReserva(reserva.consultarHabitacion(Integer.parseInt(comboBox_HabitacionesDisponibles.getSelectedItem().toString())).getCodigoReservaActiva(), true));
        parent.cambiarPanel(new panel_FacturaElectronica(parent, reserva.consultarHabitacion(Integer.parseInt(comboBox_HabitacionesDisponibles.getSelectedItem().toString())).getIdHabitacion()));
        parent.setEnabled(true);
        parent.setExtendedState(Hosys.MAXIMIZED_BOTH);
        dispose();
    }//GEN-LAST:event_button_GenerarFacturaActionPerformed

    private void button_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_VolverActionPerformed
        dispose();
    }//GEN-LAST:event_button_VolverActionPerformed

    private void label_TituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_label_TituloKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_label_TituloKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_GenerarFactura;
    private javax.swing.JButton button_Volver;
    private javax.swing.JComboBox comboBox_HabitacionesDisponibles;
    private javax.swing.JLabel label_HabitacionesDisponibles;
    private javax.swing.JLabel label_Info;
    private javax.swing.JLabel label_Titulo;
    private javax.swing.JPanel panel_HabitacionesDisponibles;
    // End of variables declaration//GEN-END:variables
}
