/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dialog_IngresarCodigoReserva.java
 *
 * Created on Oct 22, 2011, 10:15:39 AM
 */
package frontera;

import utilidades.ValidarEntrada;
import control.BusquedaDeHabitaciones;
import control.AdministrarReserva;
import entidad.Reserva;
import frontera.Hosys;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**Permite la consulta de una reserva, mediante un código de reservación
 * proporcionado tras haber realizado la reserva satisfactoriamente.
 * @author Julian Cárdenas
 */
public class dialog_ConsultarReserva extends javax.swing.JDialog {

    private Hosys parent;
    private BusquedaDeHabitaciones controlHab = new BusquedaDeHabitaciones();

    /** Creates new form dialog_IngresarCodigoReserva */
    public dialog_ConsultarReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (Hosys) parent;
        this.setTitle("Hosys - Consultar Reserva");
        radioButton_CodigoDeReserva.requestFocusInWindow();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_BuscarPor = new javax.swing.ButtonGroup();
        label_Titulo = new javax.swing.JLabel();
        panel_IngresoBusqueda = new javax.swing.JPanel();
        textField_BuscarPor = new javax.swing.JTextField();
        label_BuscarPor = new javax.swing.JLabel();
        panel_TipoDeBusqueda = new javax.swing.JPanel();
        radioButton_CodigoDeReserva = new javax.swing.JRadioButton();
        radioButton_DNI = new javax.swing.JRadioButton();
        button_Buscar = new javax.swing.JButton();
        button_Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hosys - Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setResizable(false);

        label_Titulo.setFont(new java.awt.Font("Ubuntu", 1, 36));
        label_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/l/calendar.png"))); // NOI18N
        label_Titulo.setText("Consultar Reserva");
        label_Titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        label_Titulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        textField_BuscarPor.setFont(new java.awt.Font("Ubuntu", 2, 15));
        textField_BuscarPor.setForeground(java.awt.Color.gray);
        textField_BuscarPor.setText("Código de reserva");
        textField_BuscarPor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textField_BuscarPorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField_BuscarPorFocusLost(evt);
            }
        });
        textField_BuscarPor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField_BuscarPorKeyReleased(evt);
            }
        });

        label_BuscarPor.setText("Código de reserva");

        javax.swing.GroupLayout panel_IngresoBusquedaLayout = new javax.swing.GroupLayout(panel_IngresoBusqueda);
        panel_IngresoBusqueda.setLayout(panel_IngresoBusquedaLayout);
        panel_IngresoBusquedaLayout.setHorizontalGroup(
            panel_IngresoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IngresoBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_BuscarPor)
                .addGap(18, 18, 18)
                .addComponent(textField_BuscarPor, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );
        panel_IngresoBusquedaLayout.setVerticalGroup(
            panel_IngresoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IngresoBusquedaLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panel_IngresoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_BuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_BuscarPor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_TipoDeBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.black, java.awt.Color.black, java.awt.Color.red), "Consultar Por:", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 24))); // NOI18N

        buttonGroup_BuscarPor.add(radioButton_CodigoDeReserva);
        radioButton_CodigoDeReserva.setSelected(true);
        radioButton_CodigoDeReserva.setText("Código de reserva");
        radioButton_CodigoDeReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_CodigoDeReservaActionPerformed(evt);
            }
        });

        buttonGroup_BuscarPor.add(radioButton_DNI);
        radioButton_DNI.setText("Documento de identidad");
        radioButton_DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_DNIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_TipoDeBusquedaLayout = new javax.swing.GroupLayout(panel_TipoDeBusqueda);
        panel_TipoDeBusqueda.setLayout(panel_TipoDeBusquedaLayout);
        panel_TipoDeBusquedaLayout.setHorizontalGroup(
            panel_TipoDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TipoDeBusquedaLayout.createSequentialGroup()
                .addComponent(radioButton_CodigoDeReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton_DNI)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        panel_TipoDeBusquedaLayout.setVerticalGroup(
            panel_TipoDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TipoDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioButton_CodigoDeReserva)
                .addComponent(radioButton_DNI))
        );

        button_Buscar.setText("Buscar reservación");
        button_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BuscarActionPerformed(evt);
            }
        });
        button_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_BuscarKeyPressed(evt);
            }
        });

        button_Volver.setText("Volver");
        button_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_TipoDeBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_IngresoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(button_Buscar)
                .addGap(18, 18, 18)
                .addComponent(button_Volver)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_TipoDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_IngresoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Volver)
                    .addComponent(button_Buscar))
                .addContainerGap())
        );

        panel_TipoDeBusqueda.getAccessibleContext().setAccessibleName("Consultar Por:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *  Si el código ingresado en el campo de texto "textField_BuscarPor"  es correcto, se procederá a mostrar los datos de dicha reserva en un
     * {@link panel_AdministrarReserva} sin poder modificarlos.
     * @param evt selección del botón "button_Buscar".
     */
    private void button_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BuscarActionPerformed
        if (textField_BuscarPor.getText().equals("Código de reserva")) {
            ArrayList<Reserva> reservas = controlHab.reservasExistentes();
            if (reservas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay Reservas", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/remove.png")));
            } else {
                parent.cambiarPanel(new panel_ReservasExistentes(parent));
                dispose();
            }

        } else {
            Reserva reserva = new AdministrarReserva().ConsultarReserva(Long.parseLong(textField_BuscarPor.getText()), radioButton_CodigoDeReserva.isSelected());
            if (reserva != null) {
                parent.cambiarPanel(new panel_AdministrarReserva(parent, 3, reserva));
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error, Reserva no encontrada!", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/remove.png")));
            }
        }
        //        Reserva reserva = new AdministrarReserva().ConsultarReserva(Long.parseLong(textField_BuscarPor.getText()), radioButton_CodigoDeReserva.isSelected());
//        if (reserva != null) {
//            parent.cambiarPanel(new panel_AdministrarReserva(parent, 3, reserva));
//            dispose();
//        } else {
//            JOptionPane.showMessageDialog(this, "Error, Reserva no encontrada!", "Error", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/remove.png")));
//        }

    }//GEN-LAST:event_button_BuscarActionPerformed
    /**
     * Interrumpirá cualquier operación realizada en el diálogo {@link dialog_BuscarReserva}, y retornará a {@link panel_Opciones}.
     * @param evt selección del botón "button_Volver"
     */
    private void button_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_VolverActionPerformed
        dispose();
    }//GEN-LAST:event_button_VolverActionPerformed
    /**
     * Cambiará la etiqueta, y texto por defecto a "Código de reserva". Además, el
     * criterio de busqueda será por código de reservación.
     * @param evt selección del radio button "radioButton_CodigoDeReserva".
     */
    private void radioButton_CodigoDeReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_CodigoDeReservaActionPerformed
        label_BuscarPor.setText("Código de reserva");
        textField_BuscarPor.setText("Código de reserva");
        button_Buscar.setEnabled(true);
    }//GEN-LAST:event_radioButton_CodigoDeReservaActionPerformed
    /**
     * Cambiará la etiqueta, y texto por defecto a "Documento de identidad". Además, el
     * criterio de busqueda será por documento de identidad.
     * @param evt selección del radio button "radioButton_DNI".
     */
    private void radioButton_DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_DNIActionPerformed
        label_BuscarPor.setText("Documento de identidad");
        textField_BuscarPor.setText("Documento de identidad");
        button_Buscar.setEnabled(false);
    }//GEN-LAST:event_radioButton_DNIActionPerformed
    /**
     * Al seleccionarse el campo de texto "textField_BuscarPor" se procederá a cambiar el estilo de
     * y el color del texto y se borrará el texto por defecto "Código de reserva" ó
     * "Documento de identidad", dependiendo cual sea el caso.
     * @param evt selección del campo de texto "textField_BuscarPor"
     */
    private void textField_BuscarPorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField_BuscarPorFocusGained
        if (textField_BuscarPor.getText().equals("Código de reserva") || textField_BuscarPor.getText().equals("Documento de identidad")) {
            textField_BuscarPor.setFont(new Font(textField_BuscarPor.getFont().getName(), Font.PLAIN, 15));
            textField_BuscarPor.setForeground(Color.BLACK);
            textField_BuscarPor.setText("");
        }
    }//GEN-LAST:event_textField_BuscarPorFocusGained
    /**
     * Al seleccionarse otro elemento del panel, se cambiará el estilo y color del
     * texto y se pondrá el texto por defecto "Código de reserva" ó
     * "Documento de identidad", dependiendo cual sea el caso.
     * @param evt de-selección del campo de texto "textField_BuscarPor".
     */
    private void textField_BuscarPorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField_BuscarPorFocusLost
        if (textField_BuscarPor.getText().equals("")) {
            textField_BuscarPor.setFont(new Font(textField_BuscarPor.getFont().getName(), Font.ITALIC, 15));
            textField_BuscarPor.setForeground(Color.GRAY);
            if (radioButton_CodigoDeReserva.isSelected()) {
                textField_BuscarPor.setText("Código de reserva");
            } else if (radioButton_DNI.isSelected()) {
                textField_BuscarPor.setText("Documento de identidad");
            }
        }
    }//GEN-LAST:event_textField_BuscarPorFocusLost
    /**
     * Permite la validación de datos en el campo de texto "textField_BuscarPor"
     * cada vez que libere una tecla. Si algún caracter es erróneo, se bloqueará el
     * boton "button_Buscar" hasta que se haya corregido el error.
     * @param evt liberación de tecla en el campo de texto "textField_BuscarPor"
     */
    private void textField_BuscarPorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_BuscarPorKeyReleased
        ValidarEntrada validador = new ValidarEntrada();
        presionarEsc(evt, this);
        if (label_BuscarPor.getText().equals("Código de reserva")) {
            if (validador.ValidarNumeros(textField_BuscarPor.getText(), 3) || (textField_BuscarPor.getText().isEmpty())) {
                button_Buscar.setEnabled(true);
                textField_BuscarPor.setForeground(Color.black);
            } else {
                textField_BuscarPor.setForeground(Color.red);
                button_Buscar.setEnabled(false);
            }
        } else if (label_BuscarPor.getText().equals("Documento de identidad")) {
            if (validador.ValidarNumeros(textField_BuscarPor.getText(), 1) || (textField_BuscarPor.getText().isEmpty())) {
                button_Buscar.setEnabled(true);
                textField_BuscarPor.setForeground(Color.black);
            } else {
                textField_BuscarPor.setForeground(Color.red);
                button_Buscar.setEnabled(false);
            }
        }
        if (textField_BuscarPor.getText().equals("")) {
            button_Buscar.setEnabled(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (button_Buscar.isEnabled()) {
                if (textField_BuscarPor.getText().equals("Código de reserva")) {
                    ArrayList<Reserva> reservas = controlHab.reservasExistentes();
                    if (reservas.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No hay Reservas", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/remove.png")));
                    } else {
                        parent.cambiarPanel(new panel_ReservasExistentes(parent));
                        dispose();
                    }

                } else {
                    Reserva reserva = new AdministrarReserva().ConsultarReserva(Long.parseLong(textField_BuscarPor.getText()), radioButton_CodigoDeReserva.isSelected());
                    if (reserva != null) {
                        parent.cambiarPanel(new panel_AdministrarReserva(parent, 3, reserva));
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error, Reserva no encontrada!", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/remove.png")));
                    }
                }
            }
        }
    }//GEN-LAST:event_textField_BuscarPorKeyReleased

    private void button_BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_BuscarKeyPressed
        Reserva reserva = new AdministrarReserva().ConsultarReserva(Long.parseLong(textField_BuscarPor.getText()), radioButton_CodigoDeReserva.isSelected());
        if (reserva != null) {
            parent.cambiarPanel(new panel_AdministrarReserva(parent, 3, reserva));
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error, Compruebe los datos ingresados", "Error", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/remove.png")));
        }

    }//GEN-LAST:event_button_BuscarKeyPressed

    /**
     * Se podrá salir del diálogo y volver al panel {@link panel_Opciones} si se
     * presiona la tecla Escape (Esc).
     * @param obj
     * @param diag
     */
    private void presionarEsc(Object obj, dialog_ConsultarReserva diag) {
        java.awt.event.KeyEvent e = (java.awt.event.KeyEvent) obj;
        if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
            diag.dispose();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_BuscarPor;
    private javax.swing.JButton button_Buscar;
    private javax.swing.JButton button_Volver;
    private javax.swing.JLabel label_BuscarPor;
    private javax.swing.JLabel label_Titulo;
    private javax.swing.JPanel panel_IngresoBusqueda;
    private javax.swing.JPanel panel_TipoDeBusqueda;
    private javax.swing.JRadioButton radioButton_CodigoDeReserva;
    private javax.swing.JRadioButton radioButton_DNI;
    private javax.swing.JTextField textField_BuscarPor;
    // End of variables declaration//GEN-END:variables
}
