/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dialog_ReservasPerdidas.java
 *
 * Created on 20-dic-2011, 18:57:46
 */
package frontera;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;
import reportes.ReporteReservasPerdidas;

/**
 *
 * @author user
 */
public class dialog_ReservasPerdidas extends javax.swing.JDialog {

    /** Creates new form dialog_ReservasPerdidas */
    public dialog_ReservasPerdidas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        SimpleDateFormat f = new SimpleDateFormat("dd' 'MMM' 'yyyy", new Locale("ES"));
        Calendar c = new GregorianCalendar();
        c.setTime(new GregorianCalendar().getTime());
        initComponents();
        label_Fecha.setText(f.format(c.getTime()).toUpperCase());
        llenarTabla();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Fecha = new javax.swing.JLabel();
        label_FechaActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ReservasPerdidas = new javax.swing.JTable();
        boton_AceptarReservasPerdidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_FechaActual.setText("Fecha Actual");

        table_ReservasPerdidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Inicial", "Fecha Final", "Habitacion", "Huésped", "Teléfono", "Costo Reserva"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_ReservasPerdidas);

        boton_AceptarReservasPerdidas.setText("Aceptar");
        boton_AceptarReservasPerdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AceptarReservasPerdidasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/l/calendar.png"))); // NOI18N
        jLabel1.setText("Reservas Perdidas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_FechaActual)
                                .addGap(27, 27, 27)
                                .addComponent(label_Fecha))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(boton_AceptarReservasPerdidas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_FechaActual)
                    .addComponent(label_Fecha))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_AceptarReservasPerdidas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_AceptarReservasPerdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AceptarReservasPerdidasActionPerformed
        ReporteReservasPerdidas res = new ReporteReservasPerdidas();
        res.GenerarReporte();
        new control.AdministrarReserva().CancelarReservasAlIniciar();
        this.dispose();
    }//GEN-LAST:event_boton_AceptarReservasPerdidasActionPerformed

    /**
     * Ingresa todos los datos de las <code>Reservas</code> dentro de la tabla del
     * dialogo
     */
    private void llenarTabla(){
        DefaultTableModel model = (DefaultTableModel) table_ReservasPerdidas.getModel();
        String[][] data = new control.AdministrarReserva().informacionReservasaCancelar();

        if (data.length != 0) {
            for (int i = 0; i < data.length; i++) {
                model.addRow(data[i]);
            }
        }
        else {
            data = new String[1][6];
            for(int j = 0; j < 6; j++){
                data[0][j] = " ";
            }
            data[0][3] = "No hay reservas perdidas!!!";

            model.addRow(data[0]);
        }

        table_ReservasPerdidas.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_AceptarReservasPerdidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Fecha;
    private javax.swing.JLabel label_FechaActual;
    private javax.swing.JTable table_ReservasPerdidas;
    // End of variables declaration//GEN-END:variables
}
