/*
 * Hosys.java
 *
 * Created on Oct 20, 2011, 10:45:56 AM
 */
package frontera;

import frontera.nuevoServicio.dialog_RegistroServicios;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Juan Manuel Martinez Romero
 */
public class Hosys extends javax.swing.JFrame {
    //TODO foco fecha de nacimiento

    /**
     * Carga El Look And Feel
     */
    public void initLookAndFeel() {
        Toolkit.getDefaultToolkit().setDynamicLayout(true);
        System.setProperty("sun.awt.noerasebackground", "true");
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        try {
            UIManager.setLookAndFeel("de.muntjak.tinylookandfeel.TinyLookAndFeel");
        } catch (Exception ex) {
            System.out.println("No Se Puede Cargar Look And Feel");
        }
    }

    /**
     * Añade al panel principal el panel enviado
     * @param panel a ser añadido al panel_Principal
     */
    public void cambiarPanel(JPanel panel) {
        panel_Principal.setVisible(false);
        panel_Principal.removeAll();
        panel_Principal.add(panel);
        panel_Principal.setSize(panel.getPreferredSize());
        panel_Principal.setVisible(true);
        this.setSize(this.getPreferredSize());
    }

    /** Creates new form Hosys */
    public Hosys() {
        //setLocationRelativeTo(null);
        initLookAndFeel();
        initComponents();
        dialog_Login login = new dialog_Login(this, true);
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        dialog_ReservasPerdidas perdidas = new dialog_ReservasPerdidas(this, true);
        perdidas.setLocationRelativeTo(null);
        perdidas.setVisible(true);
        cambiarPanel(new panel_Opciones(this));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Principal = new javax.swing.JPanel();
        jMenuBar_Opciones = new javax.swing.JMenuBar();
        menu_AdministrarReservacion = new javax.swing.JMenu();
        menuItem_AddReservacion = new javax.swing.JMenuItem();
        menuItem_ModificarReservacion = new javax.swing.JMenuItem();
        menuItem_SearchReservacion = new javax.swing.JMenuItem();
        menuItem_DeleteReservacion = new javax.swing.JMenuItem();
        menu_AdministrarServicios = new javax.swing.JMenu();
        menuItem_RegistrarServicio = new javax.swing.JMenuItem();
        menuItem_BuscarServicio = new javax.swing.JMenuItem();
        menu_Registro = new javax.swing.JMenu();
        menuItem_CheckIn = new javax.swing.JMenuItem();
        menuItem_CheckOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hosys - Sistema De Administracion De Reservas Y Servicios");
        setEnabled(false);

        panel_Principal.setLayout(new java.awt.BorderLayout());

        menu_AdministrarReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/s/calendar.png"))); // NOI18N
        menu_AdministrarReservacion.setText("Administrar Reserva");

        menuItem_AddReservacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuItem_AddReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/calendar.png"))); // NOI18N
        menuItem_AddReservacion.setText("Añadir Reservacion");
        menuItem_AddReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_AddReservacionActionPerformed(evt);
            }
        });
        menu_AdministrarReservacion.add(menuItem_AddReservacion);

        menuItem_ModificarReservacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        menuItem_ModificarReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/tools.png"))); // NOI18N
        menuItem_ModificarReservacion.setText("Modificar Reserva");
        menuItem_ModificarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ModificarReservacionActionPerformed(evt);
            }
        });
        menu_AdministrarReservacion.add(menuItem_ModificarReservacion);

        menuItem_SearchReservacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuItem_SearchReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/search.png"))); // NOI18N
        menuItem_SearchReservacion.setText("Consultar Reserva");
        menuItem_SearchReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_SearchReservacionActionPerformed(evt);
            }
        });
        menu_AdministrarReservacion.add(menuItem_SearchReservacion);

        menuItem_DeleteReservacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItem_DeleteReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/remove.png"))); // NOI18N
        menuItem_DeleteReservacion.setText("Cancelar Reserva");
        menuItem_DeleteReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_DeleteReservacionActionPerformed(evt);
            }
        });
        menu_AdministrarReservacion.add(menuItem_DeleteReservacion);

        jMenuBar_Opciones.add(menu_AdministrarReservacion);

        menu_AdministrarServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/s/shopping_cart.png"))); // NOI18N
        menu_AdministrarServicios.setText("Servicios");

        menuItem_RegistrarServicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menuItem_RegistrarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/add.png"))); // NOI18N
        menuItem_RegistrarServicio.setText("Registrar Servicio");
        menuItem_RegistrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_RegistrarServicioActionPerformed(evt);
            }
        });
        menu_AdministrarServicios.add(menuItem_RegistrarServicio);

        menuItem_BuscarServicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menuItem_BuscarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/search.png"))); // NOI18N
        menuItem_BuscarServicio.setText("Consultar Servicio");
        menuItem_BuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_BuscarServicioActionPerformed(evt);
            }
        });
        menu_AdministrarServicios.add(menuItem_BuscarServicio);

        jMenuBar_Opciones.add(menu_AdministrarServicios);

        menu_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/s/user.png"))); // NOI18N
        menu_Registro.setText("Registro De Huespedes");

        menuItem_CheckIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        menuItem_CheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/download.png"))); // NOI18N
        menuItem_CheckIn.setText("Check-In");
        menuItem_CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_CheckInActionPerformed(evt);
            }
        });
        menu_Registro.add(menuItem_CheckIn);

        menuItem_CheckOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menuItem_CheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/m/upload.png"))); // NOI18N
        menuItem_CheckOut.setText("Check-Out");
        menuItem_CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_CheckOutActionPerformed(evt);
            }
        });
        menu_Registro.add(menuItem_CheckOut);

        jMenuBar_Opciones.add(menu_Registro);

        setJMenuBar(jMenuBar_Opciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Añade un nuevo panel_AdministrarReserva al panelPrincipal
     * @param evt evento que activa menuItem_AddReservacion
     */
    private void menuItem_AddReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_AddReservacionActionPerformed
        cambiarPanel(new panel_AdministrarReserva(this, 1, null));
    }//GEN-LAST:event_menuItem_AddReservacionActionPerformed
    /**
     * Abre un nuevo cuadro de dialogo que permitirá Modificar una reserva
     * @param evt evento que activa menuItem_ModificarReservacion
     */
    private void menuItem_ModificarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ModificarReservacionActionPerformed
        dialog_IngresarCodigoReserva modificarReserva = new dialog_IngresarCodigoReserva(this, true, 1);
        modificarReserva.setLocationRelativeTo(this);
        modificarReserva.setVisible(true);
    }//GEN-LAST:event_menuItem_ModificarReservacionActionPerformed
    /**
     * Abre un nuevo cuadro de dialogo que permitirá Buscar una reserva
     * @param evt evento que activa menuItem_SearchReservacion
     */
    private void menuItem_SearchReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_SearchReservacionActionPerformed
        dialog_ConsultarReserva buscarReserva = new dialog_ConsultarReserva(this, true);
        buscarReserva.setLocationRelativeTo(this);
        buscarReserva.setVisible(true);
    }//GEN-LAST:event_menuItem_SearchReservacionActionPerformed
    /**
     * Abre un nuevo cuadro de dialogo que permitirá Borrar una reserva
     * @param evt evento que activa menuItem_DeleteReservacion
     */
    private void menuItem_DeleteReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_DeleteReservacionActionPerformed
        dialog_IngresarCodigoReserva modificarReserva = new dialog_IngresarCodigoReserva(this, true, 2);
        modificarReserva.setLocationRelativeTo(this);
        modificarReserva.setVisible(true);
    }//GEN-LAST:event_menuItem_DeleteReservacionActionPerformed
    /**
     * Abre un nuevo cuadro de dialogo que permitirá hacer el Check-In
     * @param evt evento que activa menuItem_CheckIn
     */
    private void menuItem_CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_CheckInActionPerformed
        dialog_IngresarCodigoReserva checkIn = new dialog_IngresarCodigoReserva(this, true, 3);
        checkIn.setLocationRelativeTo(this);
        checkIn.setVisible(true);
    }//GEN-LAST:event_menuItem_CheckInActionPerformed
    /**
     * Abre un nuevo cuadro de dialogo que permitirá Registrar un servicio
     * @param evt evento que activa menuItem_RegistrarServicio
     */
    private void menuItem_RegistrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_RegistrarServicioActionPerformed
        dialog_RegistroServicios registrar = new dialog_RegistroServicios(this, true);
        registrar.setLocationRelativeTo(this);
        registrar.setVisible(true);
    }//GEN-LAST:event_menuItem_RegistrarServicioActionPerformed
    /**
     * Abre un nuevo cuadro de dialogo que permitirá Buscar un servicio
     * @param evt evento que activa menuItem_BuscarServicio
     */
    private void menuItem_BuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_BuscarServicioActionPerformed
        dialog_ConsultarServicios consultarServicio = new dialog_ConsultarServicios(this, true);
        consultarServicio.setLocationRelativeTo(this);
        consultarServicio.setVisible(true);
    }//GEN-LAST:event_menuItem_BuscarServicioActionPerformed

    private void menuItem_CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_CheckOutActionPerformed
        dialog_CheckOut checkOut = new dialog_CheckOut(this, true);
        checkOut.setLocationRelativeTo(this);
        checkOut.setVisible(true);
    }//GEN-LAST:event_menuItem_CheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Creacion Del Recepcionista
        /*ArrayList<Recepcionista> recepcionistas = new ArrayList<Recepcionista>();
        Recepcionista recepcionista = new Recepcionista("admin", "admin");
        recepcionistas.add(recepcionista);
        mHoSYS.setRecepcionista(recepcionistas);*/
        //Creacion De Las Habitaciones
        /*ArrayList<Habitacion> habitaciones = new ArrayList<Habitacion>();
        Habitacion habitacion = new Habitacion(401);
        Habitacion habitacion1 = new Habitacion(402);
        Habitacion habitacion2 = new Habitacion(403);
        Habitacion habitacion3 = new Habitacion(404);
        Habitacion habitacion4 = new Habitacion(405);
        Habitacion habitacion5 = new Habitacion(406);

        habitaciones.add(habitacion);
        habitaciones.add(habitacion1);
        habitaciones.add(habitacion2);
        habitaciones.add(habitacion3);
        habitaciones.add(habitacion4);
        habitaciones.add(habitacion5);

        mHoSYS.setHabitacion(habitaciones);

        //Creacion De Un Huesped
        Calendar nac = new GregorianCalendar(1992, 1, 1);
        Calendar ini = new GregorianCalendar(2011, 10, 29);
        Calendar fin = new GregorianCalendar(2011, 10, 30);
        Huesped carlos = new Huesped("Carlos", "Pitufin", 1, nac.getTime(), "Colombia", "Bogota", 68138, "44646", "Visa", "Europeo");

        //Creacion De La Reserva
        ControlDeHabitaciones reserva = new ControlDeHabitaciones();
        reserva.HacerReserva(habitacion.getId(), carlos, ini.getTime(), fin.getTime());*/

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Hosys hosys = new Hosys();
                hosys.setLocationRelativeTo(null);
                hosys.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar_Opciones;
    private javax.swing.JMenuItem menuItem_AddReservacion;
    private javax.swing.JMenuItem menuItem_BuscarServicio;
    private javax.swing.JMenuItem menuItem_CheckIn;
    private javax.swing.JMenuItem menuItem_CheckOut;
    private javax.swing.JMenuItem menuItem_DeleteReservacion;
    private javax.swing.JMenuItem menuItem_ModificarReservacion;
    private javax.swing.JMenuItem menuItem_RegistrarServicio;
    private javax.swing.JMenuItem menuItem_SearchReservacion;
    private javax.swing.JMenu menu_AdministrarReservacion;
    private javax.swing.JMenu menu_AdministrarServicios;
    private javax.swing.JMenu menu_Registro;
    private javax.swing.JPanel panel_Principal;
    // End of variables declaration//GEN-END:variables
}
