/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panel_ReservasExistentes.java
 *
 * Created on 15-ene-2012, 12:27:48
 */

package frontera;


import control.AdministrarReserva;
import control.BusquedaDeHabitaciones;
import entidad.Reserva;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joanna 8a
 */
public class panel_ReservasExistentes extends javax.swing.JPanel {
 private Hosys parent;
  private BusquedaDeHabitaciones controlHab = new BusquedaDeHabitaciones();
    /** Creates new form panel_ReservasExistentes */
    public panel_ReservasExistentes(Hosys parent) {
        this.parent=parent;
        initComponents();
        llenarTablaReservas();
        //jLabelReservas.setIcon((Icon) getIconImage());
    }
private void llenarTablaReservas(){
ArrayList<Reserva> reservas= controlHab.reservasExistentes();
    DefaultTableModel modelo = (DefaultTableModel) jTable_listadoReservas.getModel();
        //int a = modelo.getRowCount() - 1;
        int filas=reservas.size()-1;
        modelo.setRowCount(filas);
//        for (int i = 0; i <= a; i++) {
//            modelo.removeRow(0);
//        }
        Object[] fila = new Object[6];
        BusquedaDeHabitaciones controlReserva = new BusquedaDeHabitaciones();
        AdministrarReserva adminReserva = new AdministrarReserva();
        for(Reserva r: reservas){

                fila[0]=r.getCodigoReserva();
                fila[1]=r.getFechaInicial();
                fila[2]=r.getFechaFinal();
                fila[3]=r.getHuesped().getNombre()+" "+r.getHuesped().getApellido();
                fila[4]=r.getHuesped().getDNI();
                fila[5]=r.getHuesped().getNumeroContacto();
                modelo.addRow(fila);

                adminReserva.CancelarReserva(Integer.parseInt("0"));// para cancelar la reserva que se iniciasliza en Hosys para que no haya problema de NullPointerException
            for (int i = 0; i < modelo.getRowCount(); i++) {
                    if (modelo.getValueAt(0, 0)==null || modelo.getValueAt(i, 4).toString().equals("0")){
             modelo.removeRow(i);
             }
            }
       }}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelReservas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_listadoReservas = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();

        jLabelReservas.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabelReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/l/reserva.png"))); // NOI18N
        jLabelReservas.setText("Reservas");

        jTable_listadoReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fecha inicial", "Fecha final", "Huésped", "Documento", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_listadoReservas);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(164, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVolver)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButtonVolver)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        parent.cambiarPanel(new panel_Opciones(parent));
    }//GEN-LAST:event_jButtonVolverActionPerformed
public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("frontera/imagenes/iconos/l/reservas.png"));
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelReservas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_listadoReservas;
    // End of variables declaration//GEN-END:variables

}
