/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dialog_RegistroServicios.java
 *
 * Created on 07-nov-2011, 11:10:37
 */
package frontera.nuevoServicio;

import control.AdministrarServicio;
import javax.swing.JPanel;

/**
 *Ventana que se encarga de mostrar el menú de servicios ofrecidos por el Hotel para registrar solicitudes de éstos
 * por el huésped y cargarlas a su cuenta
 * @author Joanna 8a
 */
public class dialog_RegistroServicios extends javax.swing.JDialog {

    /** Creates new form dialog_RegistroServicios */
    public dialog_RegistroServicios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Hosys - Registrar Servicio");
        changePanel(new panel_Restaurante(this));
    }

    /**
     * Cambia el panel principal al servicio seleccionado
     * @param panel_Servicios Panel del servicio
     */
    public void changePanel(JPanel panel_Servicio) {
        panel_Servicios.setVisible(false);
        panel_Servicios.removeAll();
        panel_Servicios.add(panel_Servicio);
        panel_Servicios.setSize(panel_Servicio.getPreferredSize());
        panel_Servicios.setVisible(true);
        this.setSize(this.getPreferredSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Servicios = new javax.swing.JLabel();
        comboBox_Servicio = new javax.swing.JComboBox();
        panel_Servicios = new javax.swing.JPanel();
        label_Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_Servicios.setText("Servicios:");

        comboBox_Servicio.setModel(new javax.swing.DefaultComboBoxModel(new AdministrarServicio().serviciosDisponibles()));
        comboBox_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_ServicioActionPerformed(evt);
            }
        });

        panel_Servicios.setLayout(new java.awt.BorderLayout());

        label_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24));
        label_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/l/heart.png"))); // NOI18N
        label_Titulo.setText("Servicios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Servicios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(label_Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_Servicios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox_Servicio, 0, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Servicios)
                    .addComponent(comboBox_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Servicios, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBox_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_ServicioActionPerformed
        System.out.println(comboBox_Servicio.getSelectedItem());
        if (comboBox_Servicio.getSelectedItem().toString().equals("Restaurante")) {
            changePanel(new panel_Restaurante(this));
        } else if (comboBox_Servicio.getSelectedItem().toString().equals("GYM") || comboBox_Servicio.getSelectedItem().toString().equals("SPA")) {
            changePanel(new panel_Gimnasio_y_Spa(this, comboBox_Servicio.getSelectedItem().toString()));
        } else if (comboBox_Servicio.getSelectedItem().toString().equals("Lavanderia")) {
            changePanel(new panel_Lavanderia(this));
        } else if (comboBox_Servicio.getSelectedItem().toString().equals("MiniBar")) {
            changePanel(new panel_MiniBar(this));
        }
}//GEN-LAST:event_comboBox_ServicioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox_Servicio;
    private javax.swing.JLabel label_Servicios;
    private javax.swing.JLabel label_Titulo;
    private javax.swing.JPanel panel_Servicios;
    // End of variables declaration//GEN-END:variables
}
