/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panel_Restaurante.java
 *
 * Created on 20/10/2011, 09:56:39 PM
 */
package frontera.nuevoServicio;

import control.AdministrarReserva;
import entidad.Habitacion;
import java.util.ArrayList;
import control.BusquedaDeHabitaciones;
import entidad.Restaurante;
import control.AdministrarServicio;
import dao.ServicioDao;
import entidad.Huesped;

/**
 *Obtiene los datos necesarios cuando el Huésped solicita el servicio de Restaurante
 * Tiene los siguientes labels con su respectivo elemento que informa sobre los datos que dichos labels indican
 * Tickets: Radio Button con label indicador de cantidad de tickets solicitadas por el huésped
 * Costo: Campo de Texto que obtiene e informa el costo del servicio solicitado y lo muestra (No editable)
 * Cuarto: ComboBox con lista de habitaciones ocupadas (No editable)
 * Titular: Nombre del titular de la habitación que solicita el servicio
 * @author Joanna 8a
 */
public class panel_Restaurante extends javax.swing.JPanel {

    dialog_RegistroServicios dRegistrar;

    /** Creates new form panel_Restaurante */
    public panel_Restaurante(dialog_RegistroServicios registrar) {
        initComponents();
        this.dRegistrar = registrar;
        llenarOcupadas();
        if (slider_Cantidad.getValue() == 0) {
            button_Cargar.setEnabled(false);
        }
    }

    private void llenarOcupadas() {
        ArrayList<Habitacion> habitacionesOcupadas = new BusquedaDeHabitaciones().habitacionesOcupadas();
        if (!habitacionesOcupadas.isEmpty()) {
            for (Habitacion h : habitacionesOcupadas) {
                comboBox_Cuarto.addItem(h.getIdHabitacion());
                button_Cargar.setEnabled(true);
                slider_Cantidad.setEnabled(true);
            }
        } else {
            button_Cargar.setEnabled(false);
            slider_Cantidad.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Tickets = new javax.swing.JLabel();
        label_Costo = new javax.swing.JLabel();
        textField_Costo = new javax.swing.JTextField();
        label_Cuarto = new javax.swing.JLabel();
        comboBox_Cuarto = new javax.swing.JComboBox();
        label_Titular = new javax.swing.JLabel();
        textField_Titular = new javax.swing.JTextField();
        button_Cargar = new javax.swing.JButton();
        button_Cancelar = new javax.swing.JButton();
        slider_Cantidad = new javax.swing.JSlider();
        label_ValorCantidad = new javax.swing.JLabel();

        label_Tickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/calculator.png"))); // NOI18N
        label_Tickets.setText("Tickets");

        label_Costo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/shopping_cart.png"))); // NOI18N
        label_Costo.setText("Costo");

        textField_Costo.setEditable(false);

        label_Cuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/home.png"))); // NOI18N
        label_Cuarto.setText("Habitacion");

        comboBox_Cuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_CuartoActionPerformed(evt);
            }
        });

        label_Titular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/user.png"))); // NOI18N
        label_Titular.setText("Titular");

        textField_Titular.setEditable(false);

        button_Cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/upload.png"))); // NOI18N
        button_Cargar.setText("Cargar");
        button_Cargar.setEnabled(false);
        button_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CargarActionPerformed(evt);
            }
        });

        button_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/remove.png"))); // NOI18N
        button_Cancelar.setText("Cancelar");
        button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancelarActionPerformed(evt);
            }
        });

        slider_Cantidad.setValue(0);
        slider_Cantidad.setEnabled(false);
        slider_Cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_CantidadStateChanged(evt);
            }
        });

        label_ValorCantidad.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(label_Tickets, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_Costo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_Cuarto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_Titular, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(button_Cargar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBox_Cuarto, 0, 162, Short.MAX_VALUE)
                    .addComponent(button_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(textField_Costo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(textField_Titular, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slider_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_ValorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_Tickets)
                    .addComponent(slider_Cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_ValorCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Costo)
                    .addComponent(textField_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Cuarto)
                    .addComponent(comboBox_Cuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Titular)
                    .addComponent(textField_Titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Cargar)
                    .addComponent(button_Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cargará el servicio a la cuenta del huésped
     */
    private void button_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CargarActionPerformed
        new AdministrarServicio().registrarServicio(new Restaurante(slider_Cantidad.getValue()),
                new BusquedaDeHabitaciones().consultarHabitacion(Integer.parseInt(comboBox_Cuarto.getSelectedItem().toString())));
        dRegistrar.dispose();
}//GEN-LAST:event_button_CargarActionPerformed
    /**
     * Sale del aplicativo de servicios
     */
    private void button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancelarActionPerformed
        dRegistrar.dispose();
}//GEN-LAST:event_button_CancelarActionPerformed
    /**
     * Muestra la cantidad de sesiones solicitadas por el huésped en un label no editable, según el movimiento del Radio Button
     */
    private void slider_CantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_CantidadStateChanged
        if (slider_Cantidad.getValue() != 0) {
            button_Cargar.setEnabled(true);
        } else {
            button_Cargar.setEnabled(false);
        }
        String valCantSlider = Integer.toString(slider_Cantidad.getValue());
        label_ValorCantidad.setText(valCantSlider);
        //TODO Eliminar al terminar persistencia
        //entidad.Restaurante rest = (entidad.Restaurante) mHoSYS.getmServicios().get(0);
        entidad.Restaurante rest = (entidad.Restaurante) new ServicioDao().buscarServicio(new Restaurante(0));
        rest.setCantidad(Integer.parseInt(label_ValorCantidad.getText()));
        rest.setCostoTotal();
        textField_Costo.setText(new Long(rest.getCostoTotal()).toString());
}//GEN-LAST:event_slider_CantidadStateChanged

    private void comboBox_CuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_CuartoActionPerformed
        Huesped huesped = new AdministrarReserva().ConsultarReserva(new BusquedaDeHabitaciones().consultarHabitacion(Integer.parseInt(comboBox_Cuarto.getSelectedItem().toString())).getCodigoReservaActiva(), true).getHuesped();
        textField_Titular.setText(huesped.getNombre() + huesped.getApellido());
    }//GEN-LAST:event_comboBox_CuartoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Cancelar;
    private javax.swing.JButton button_Cargar;
    private javax.swing.JComboBox comboBox_Cuarto;
    private javax.swing.JLabel label_Costo;
    private javax.swing.JLabel label_Cuarto;
    private javax.swing.JLabel label_Tickets;
    private javax.swing.JLabel label_Titular;
    private javax.swing.JLabel label_ValorCantidad;
    private javax.swing.JSlider slider_Cantidad;
    private javax.swing.JTextField textField_Costo;
    private javax.swing.JTextField textField_Titular;
    // End of variables declaration//GEN-END:variables
}
