/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panel_Gimnasio_y_Spa.java
 *
 * Created on 20/10/2011, 09:57:20 PM
 */
package frontera.nuevoServicio;

import control.AdministrarReserva;
import control.AdministrarServicio;
import control.BusquedaDeHabitaciones;
import dao.ServicioDao;
import entidad.GYM;
//import entidad.GYM;
//import entidad.SPA;
import entidad.Habitacion;
import entidad.Huesped;
import entidad.SPA;
import java.util.ArrayList;

/**
 * Obtiene los datos necesarios cuando el Huésped solicita el servicio de Gimnasio o Spa.
 * Tiene los siguientes labels con su respectivo elemento que informa sobre los datos que dichos labels indican
 * Sesiones: Radio Button con label indicador de cantidad de sesiones solicitadas por el ususario
 * Costo: Campo de Texto que obtiene e informa el costo del servicio solicitado y lo muestra (No editable)
 * Cuarto: ComboBox con lista de habitaciones ocupadas (No editable)
 * Titular: Nombre del titular de la habitación que solicita el servicio
 * @author Joanna 8a
 */
public class panel_Gimnasio_y_Spa extends javax.swing.JPanel {

    private dialog_RegistroServicios dRegistrar;
    private BusquedaDeHabitaciones reservar = new BusquedaDeHabitaciones();
    private AdministrarServicio registrar = new AdministrarServicio();
    private String nombre;

    /** Creates new form panel_Gimnasio_y_Spa */
    public panel_Gimnasio_y_Spa(dialog_RegistroServicios registrar, String nombre) {
        initComponents();
        this.dRegistrar = registrar;
        this.nombre = nombre;
        llenarOcupadas();
        if (slider_Cantidad.getValue() == 0){
            button_Cargar.setEnabled(false);
        }
    }

    private void llenarOcupadas() {
        ArrayList<Habitacion> habitacionesOcupadas = new BusquedaDeHabitaciones().habitacionesOcupadas();
        if (!habitacionesOcupadas.isEmpty()) {
            for (Habitacion h : habitacionesOcupadas) {
                comboBox_Cuarto.addItem(h.getIdHabitacion());
                button_Cargar.setEnabled(true);
                slider_Cantidad.setEnabled(true);
            }
        } else {
            button_Cargar.setEnabled(false);
            slider_Cantidad.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Cantidad = new javax.swing.JLabel();
        label_Costo = new javax.swing.JLabel();
        textField_Costo = new javax.swing.JTextField();
        label_Cuarto = new javax.swing.JLabel();
        comboBox_Cuarto = new javax.swing.JComboBox();
        label_Titular = new javax.swing.JLabel();
        textField_Titular = new javax.swing.JTextField();
        button_Cargar = new javax.swing.JButton();
        button_CancelServices = new javax.swing.JButton();
        slider_Cantidad = new javax.swing.JSlider();
        label_ValorCantidad = new javax.swing.JLabel();

        label_Cantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/calculator.png"))); // NOI18N
        label_Cantidad.setText("Sesiones");

        label_Costo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/shopping_cart.png"))); // NOI18N
        label_Costo.setText("Costo:");

        textField_Costo.setEditable(false);

        label_Cuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/home.png"))); // NOI18N
        label_Cuarto.setText("Habitacion");

        comboBox_Cuarto.setModel(new javax.swing.DefaultComboBoxModel());
        comboBox_Cuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_CuartoActionPerformed(evt);
            }
        });

        label_Titular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/user.png"))); // NOI18N
        label_Titular.setText("Titular");

        textField_Titular.setEditable(false);

        button_Cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/upload.png"))); // NOI18N
        button_Cargar.setText("Cargar");
        button_Cargar.setEnabled(false);
        button_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CargarActionPerformed(evt);
            }
        });

        button_CancelServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/remove.png"))); // NOI18N
        button_CancelServices.setText("Cancelar");
        button_CancelServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancelServicesActionPerformed(evt);
            }
        });

        slider_Cantidad.setMaximum(20);
        slider_Cantidad.setValue(0);
        slider_Cantidad.setEnabled(false);
        slider_Cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_CantidadStateChanged(evt);
            }
        });

        label_ValorCantidad.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Costo)
                    .addComponent(label_Cuarto)
                    .addComponent(label_Titular)
                    .addComponent(button_Cargar)
                    .addComponent(label_Cantidad))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_CancelServices)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textField_Titular, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox_Cuarto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_Costo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slider_Cantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(label_ValorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_ValorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Cantidad)
                    .addComponent(slider_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Costo)
                    .addComponent(textField_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Cuarto)
                    .addComponent(comboBox_Cuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Titular)
                    .addComponent(textField_Titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Cargar)
                    .addComponent(button_CancelServices))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cargará el servicio a la cuenta del huésped
     */
    private void button_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CargarActionPerformed
        if (nombre.equals("GYM")) {
            registrar.registrarServicio(new GYM(slider_Cantidad.getValue()),
                    new BusquedaDeHabitaciones().consultarHabitacion(Integer.parseInt(comboBox_Cuarto.getSelectedItem().toString())));
        } else {
            registrar.registrarServicio(new SPA(slider_Cantidad.getValue()),
                    new BusquedaDeHabitaciones().consultarHabitacion(Integer.parseInt(comboBox_Cuarto.getSelectedItem().toString())));
        }
        //registrar.registrarServicio(, null)
        dRegistrar.dispose();
}//GEN-LAST:event_button_CargarActionPerformed
    /**
     * Sale del aplicativo de servicios
     */
    private void button_CancelServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancelServicesActionPerformed
        dRegistrar.dispose();
}//GEN-LAST:event_button_CancelServicesActionPerformed
    /**
     * Muestra la cantidad de sesiones solicitadas por el huésped en un label no editable, según el movimiento del Radio Button
     */
    private void slider_CantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_CantidadStateChanged
        if (slider_Cantidad.getValue() != 0) {
            button_Cargar.setEnabled(true);
        } else {
            button_Cargar.setEnabled(false);
        }
        String valCantSlider = Integer.toString(slider_Cantidad.getValue());
        label_ValorCantidad.setText(valCantSlider);
        if (nombre.equals("GYM")) {
            //TODO Eliminar al terminar persistencia
            //entidad.GYM gym = (entidad.GYM) mHoSYS.getmServicios().get(3);
            entidad.GYM gym = (entidad.GYM) new ServicioDao().buscarServicio(new GYM(0));
            gym.setCantidad(Integer.parseInt(label_ValorCantidad.getText()));
            gym.setCostoTotal();
            textField_Costo.setText(new Long(gym.getCostoTotal()).toString());
        } else {
            //TODO Eliminar al terminar persistencia
            //entidad.SPA spa = (entidad.SPA) mHoSYS.getmServicios().get(2);
            entidad.SPA spa = (entidad.SPA) new ServicioDao().buscarServicio(new SPA(0));
            spa.setCantidad(Integer.parseInt(label_ValorCantidad.getText()));
            spa.setCostoTotal();
            textField_Costo.setText(new Long(spa.getCostoTotal()).toString());
        }
}//GEN-LAST:event_slider_CantidadStateChanged

    private void comboBox_CuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_CuartoActionPerformed
        Huesped huesped = new AdministrarReserva().ConsultarReserva(new BusquedaDeHabitaciones().consultarHabitacion(Integer.parseInt(comboBox_Cuarto.getSelectedItem().toString())).getCodigoReservaActiva(), true).getHuesped();
        textField_Titular.setText(huesped.getNombre() + huesped.getApellido());
    }//GEN-LAST:event_comboBox_CuartoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_CancelServices;
    private javax.swing.JButton button_Cargar;
    private javax.swing.JComboBox comboBox_Cuarto;
    private javax.swing.JLabel label_Cantidad;
    private javax.swing.JLabel label_Costo;
    private javax.swing.JLabel label_Cuarto;
    private javax.swing.JLabel label_Titular;
    private javax.swing.JLabel label_ValorCantidad;
    private javax.swing.JSlider slider_Cantidad;
    private javax.swing.JTextField textField_Costo;
    private javax.swing.JTextField textField_Titular;
    // End of variables declaration//GEN-END:variables
}
