/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panel_Lavanderia.java
 *
 * Created on 20/10/2011, 10:00:12 PM
 */
package frontera.nuevoServicio;

import control.AdministrarReserva;
import control.AdministrarServicio;
import entidad.Habitacion;
import control.BusquedaDeHabitaciones;
import dao.ServicioDao;
import entidad.Huesped;
import entidad.Lavanderia;
import java.util.ArrayList;

/**
 *Clase Lavandería que obtiene los datos necesarios cuando el Huésped solicita el servicio de Lavandería
 * Tiene los siguientes labels con su respectivo elemento que informa sobre los datos que dichos labels indican
 * Libras: Radio Button con label indicador de cantidad de libras a lavar de ropa del huésped
 * Costo: Campo de Texto que obtiene e informa el costo del servicio solicitado y lo muestra (No editable)
 * Cuarto: ComboBox con lista de habitaciones ocupadas (No editable)
 * Titular: Nombre del titular de la habitación que solicita el servicio
 * @author Joanna 8a
 */
public class panel_Lavanderia extends javax.swing.JPanel {

    dialog_RegistroServicios dRegistrar;

    /** Creates new form panel_Lavanderia */
    public panel_Lavanderia(dialog_RegistroServicios registrar) {
        initComponents();
        this.dRegistrar = registrar;
        llenarOcupadas();
        if (slider_CantidadTotal.getValue() == 0) {
            button_Cargar.setEnabled(false);
        }
    }

    private void llenarOcupadas() {
        ArrayList<Habitacion> habitacionesOcupadas = new BusquedaDeHabitaciones().habitacionesOcupadas();
        if (!habitacionesOcupadas.isEmpty()) {
            for (Habitacion h : habitacionesOcupadas) {
                comboBox_Cuarto.addItem(h.getIdHabitacion());
                button_Cargar.setEnabled(true);
                slider_CantidadTotal.setEnabled(true);
            }
        } else {
            button_Cargar.setEnabled(false);
            slider_CantidadTotal.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroServicios = new javax.swing.JPanel();
        label_Cantidad = new javax.swing.JLabel();
        label_Costo = new javax.swing.JLabel();
        textField_Costo = new javax.swing.JTextField();
        label_Cuarto = new javax.swing.JLabel();
        comboBox_Cuarto = new javax.swing.JComboBox();
        label_Titular = new javax.swing.JLabel();
        textField_Titular = new javax.swing.JTextField();
        button_Cargar = new javax.swing.JButton();
        button_CancelarServicios = new javax.swing.JButton();
        slider_CantidadTotal = new javax.swing.JSlider();
        label_ValorCantidad = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        label_Cantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/calculator.png"))); // NOI18N
        label_Cantidad.setText("Libras");

        label_Costo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/shopping_cart.png"))); // NOI18N
        label_Costo.setText("Costo:");

        textField_Costo.setEditable(false);

        label_Cuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/home.png"))); // NOI18N
        label_Cuarto.setText("Habitacion");

        comboBox_Cuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_CuartoActionPerformed(evt);
            }
        });

        label_Titular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/user.png"))); // NOI18N
        label_Titular.setText("Titular");

        textField_Titular.setEditable(false);

        button_Cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/upload.png"))); // NOI18N
        button_Cargar.setText("Cargar");
        button_Cargar.setEnabled(false);
        button_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CargarActionPerformed(evt);
            }
        });

        button_CancelarServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontera/imagenes/iconos/xS/remove.png"))); // NOI18N
        button_CancelarServicios.setText("Cancelar");
        button_CancelarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancelarServiciosActionPerformed(evt);
            }
        });

        slider_CantidadTotal.setValue(0);
        slider_CantidadTotal.setEnabled(false);
        slider_CantidadTotal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_CantidadTotalStateChanged(evt);
            }
        });

        label_ValorCantidad.setText("0");

        javax.swing.GroupLayout registroServiciosLayout = new javax.swing.GroupLayout(registroServicios);
        registroServicios.setLayout(registroServiciosLayout);
        registroServiciosLayout.setHorizontalGroup(
            registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroServiciosLayout.createSequentialGroup()
                .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Costo)
                    .addComponent(label_Cuarto)
                    .addComponent(label_Titular)
                    .addComponent(button_Cargar)
                    .addComponent(label_Cantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_CancelarServicios)
                    .addGroup(registroServiciosLayout.createSequentialGroup()
                        .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textField_Titular, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox_Cuarto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_Costo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slider_CantidadTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(label_ValorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        registroServiciosLayout.setVerticalGroup(
            registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroServiciosLayout.createSequentialGroup()
                .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label_ValorCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(slider_CantidadTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroServiciosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(label_Cantidad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Costo)
                    .addComponent(textField_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Cuarto)
                    .addComponent(comboBox_Cuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Titular)
                    .addComponent(textField_Titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registroServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Cargar)
                    .addComponent(button_CancelarServicios))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(registroServicios, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cargará el servicio a la cuenta del huésped
     */
    private void button_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CargarActionPerformed
        new AdministrarServicio().registrarServicio(new Lavanderia(slider_CantidadTotal.getValue()),
                new BusquedaDeHabitaciones().consultarHabitacion(Integer.parseInt(comboBox_Cuarto.getSelectedItem().toString())));
        dRegistrar.dispose();
}//GEN-LAST:event_button_CargarActionPerformed
    /**
     * Sale del aplicativo de servicios
     */
    private void button_CancelarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancelarServiciosActionPerformed
        dRegistrar.dispose();
}//GEN-LAST:event_button_CancelarServiciosActionPerformed
    /**
     * Muestra la cantidad de sesiones solicitadas por el huésped en un label no editable, según el movimiento del Radio Button
     */
    private void slider_CantidadTotalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_CantidadTotalStateChanged
        if (slider_CantidadTotal.getValue() != 0) {
            button_Cargar.setEnabled(true);
        } else {
            button_Cargar.setEnabled(false);
        }
        String valCantSlider = Integer.toString(slider_CantidadTotal.getValue());
        label_ValorCantidad.setText(valCantSlider);
        //TODO Eliminar al terminar persistencia
        //entidad.Lavanderia lav = (entidad.Lavanderia) mHoSYS.getmServicios().get(1);
        entidad.Lavanderia lav = (entidad.Lavanderia) new ServicioDao().buscarServicio(new Lavanderia(0));
        lav.setCantidad(Integer.parseInt(label_ValorCantidad.getText()));
        lav.setCostoTotal();
        textField_Costo.setText(new Long(lav.getCostoTotal()).toString());
}//GEN-LAST:event_slider_CantidadTotalStateChanged

    private void comboBox_CuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_CuartoActionPerformed
        Huesped huesped = new AdministrarReserva().ConsultarReserva(new BusquedaDeHabitaciones().consultarHabitacion(Integer.parseInt(comboBox_Cuarto.getSelectedItem().toString())).getCodigoReservaActiva(), true).getHuesped();
        textField_Titular.setText(huesped.getNombre() + huesped.getApellido());
    }//GEN-LAST:event_comboBox_CuartoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_CancelarServicios;
    private javax.swing.JButton button_Cargar;
    private javax.swing.JComboBox comboBox_Cuarto;
    private javax.swing.JLabel label_Cantidad;
    private javax.swing.JLabel label_Costo;
    private javax.swing.JLabel label_Cuarto;
    private javax.swing.JLabel label_Titular;
    private javax.swing.JLabel label_ValorCantidad;
    private javax.swing.JPanel registroServicios;
    private javax.swing.JSlider slider_CantidadTotal;
    private javax.swing.JTextField textField_Costo;
    private javax.swing.JTextField textField_Titular;
    // End of variables declaration//GEN-END:variables
}
